import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PAKSHALA",
  description: "Generated by create next app",
  icons: {
    icon: "/tab-v2.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        theme: neobrutalism,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} `}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Toaster richColors />
          <footer className=" px-4 py-8 border-t ">
            <div className="max-w-6xl mx-auto flex justify-center items-center ">
              <p className="text-stone-500 text-sm">
                {" "}
                made with 💗 by Jainil Prajapati
              </p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
